sudo: required
services:
  - docker

before_install:
  ### Prepare test images to run application tests
  - docker build -t andystoica/fancyfib-client-test -f ./client/Dockerfile.dev ./client

script:
  ### Run tests for the client application
  - docker run -e CI=true andystoica/fancyfib-client-test npm test

after_success:
  ### Build application containers
  - docker build -t andystoica/fancyfib-client ./client
  - docker build -t andystoica/fancyfib-api ./api
  - docker build -t andystoica/fancyfib-worker ./worker
  - docker build -t andystoica/fancyfib-router ./router
  ### Push containers to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push andystoica/fancyfib-client
  - docker push andystoica/fancyfib-api
  - docker push andystoica/fancyfib-worker
  - docker push andystoica/fancyfib-router

deploy:
  ### Deploy to AWS
  provider: elasticbeanstalk
  region: eu-west-2
  app: fancy-fib-app
  env: FancyFibApp-env
  bucket_name: elasticbeanstalk-eu-west-2-914467317987
  bucket_path: fancy-fib-app
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
