version: "3"
services:
  router:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./router
    ports:
      - "3050:80"

  postgres:
    image: "postgres:latest"

  redis:
    image: "redis:latest"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    # All default passwords and ports bellow come from base empty
    # images for this demo only. Production values are always stored
    # encrypted and passed as environment varibales during deployment.
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
    depends_on:
      - postgres

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    restart: always
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
